"""
FastAPI application entrypoint.

Run with:
    uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

Then visit http://localhost:8000/docs for interactive Swagger UI docs
(auto-generated by FastAPI from the Pydantic schemas in app/api/schemas.py).
"""

from __future__ import annotations

from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.api.routes import router
from app.core.config import get_settings
from app.core.logging_config import logger

settings = get_settings()


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Startup/shutdown hooks. Logs which LLM backend mode the app is running in."""
    mode = (
        "LIVE (AWS Bedrock)"
        if (settings.bedrock_available and not settings.use_mock_llm)
        else "MOCK (offline)"
    )
    logger.info(f"Starting {settings.app_name} | env={settings.app_env} | LLM mode={mode}")
    yield
    logger.info(f"Shutting down {settings.app_name}")


app = FastAPI(
    title="SupplyChain Sentinel API",
    description=(
        "Multi-agent agentic system for autonomous supply chain stress-testing "
        "and predictive YoY performance reporting. Built with LangGraph, FastAPI, "
        "and AWS Bedrock."
    ),
    version="1.0.0",
    lifespan=lifespan,
)

# Permissive CORS for local development / demo purposes.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(router, prefix="/api/v1")


@app.get("/", tags=["Root"])
def root() -> dict:
    return {
        "service": settings.app_name,
        "status": "running",
        "docs": "/docs",
        "health": "/api/v1/health",
    }
